schemaName: sursen_encrypt
dataSources:
  unique_ds:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/sursen_encrypt?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
  - !ENCRYPT
    encryptors:
      aes_encryptor:
        type: AES
        props:
          aes-key-value: 123456abc
#      sm4_encryptor:
#        type: SM4
#        props:
#          sm4-key: 4D744E003D713D054E7E407C350E447E
#          sm4-mode: ECB
#          sm4-padding: PKCS5Padding
    tables:
      tb_f_user10:
        columns:
          birthday:
            plainColumn: birthday_plain
            cipherColumn: birthday_cipher
            encryptorName: aes_encryptor
          name:
            plainColumn: name_plain
            cipherColumn: name_cipher
            encryptorName: aes_encryptor
          contact_person:
            plainColumn: contact_person_plain
            cipherColumn: contact_person_cipher
            encryptorName: aes_encryptor
      tb_f_user_cert10:
        columns:
          cert_no:
            plainColumn: cert_no_plain
            cipherColumn: cert_no_cipher
            encryptorName: aes_encryptor
          effective_date:
            plainColumn: effective_date_plain
            cipherColumn: effective_date_cipher
            encryptorName: aes_encryptor
          expire_date:
            plainColumn: expire_date_plain
            cipherColumn: expire_date_cipher
            encryptorName: aes_encryptor
      tb_f_user_contact10:
        columns:
          phone:
            plainColumn: phone_plain
            cipherColumn: phone_cipher
            encryptorName: aes_encryptor
          email:
            plainColumn: email_plain
            cipherColumn: email_cipher
            encryptorName: aes_encryptor

      tb_f_user100:
        columns:
          birthday:
            plainColumn: birthday_plain
            cipherColumn: birthday_cipher
            encryptorName: aes_encryptor
          name:
            plainColumn: name_plain
            cipherColumn: name_cipher
            encryptorName: aes_encryptor
          contact_person:
            plainColumn: contact_person_plain
            cipherColumn: contact_person_cipher
            encryptorName: aes_encryptor
      tb_f_user_cert100:
        columns:
          cert_no:
            plainColumn: cert_no_plain
            cipherColumn: cert_no_cipher
            encryptorName: aes_encryptor
          effective_date:
            plainColumn: effective_date_plain
            cipherColumn: effective_date_cipher
            encryptorName: aes_encryptor
          expire_date:
            plainColumn: expire_date_plain
            cipherColumn: expire_date_cipher
            encryptorName: aes_encryptor
      tb_f_user_contact100:
        columns:
          phone:
            plainColumn: phone_plain
            cipherColumn: phone_cipher
            encryptorName: aes_encryptor
          email:
            plainColumn: email_plain
            cipherColumn: email_cipher
            encryptorName: aes_encryptor

      tb_f_user1000:
        columns:
          birthday:
            plainColumn: birthday_plain
            cipherColumn: birthday_cipher
            encryptorName: aes_encryptor
          name:
            plainColumn: name_plain
            cipherColumn: name_cipher
            encryptorName: aes_encryptor
          contact_person:
            plainColumn: contact_person_plain
            cipherColumn: contact_person_cipher
            encryptorName: aes_encryptor
      tb_f_user_cert1000:
        columns:
          cert_no:
            plainColumn: cert_no_plain
            cipherColumn: cert_no_cipher
            encryptorName: aes_encryptor
          effective_date:
            plainColumn: effective_date_plain
            cipherColumn: effective_date_cipher
            encryptorName: aes_encryptor
          expire_date:
            plainColumn: expire_date_plain
            cipherColumn: expire_date_cipher
            encryptorName: aes_encryptor
      tb_f_user_contact1000:
        columns:
          phone:
            plainColumn: phone_plain
            cipherColumn: phone_cipher
            encryptorName: aes_encryptor
          email:
            plainColumn: email_plain
            cipherColumn: email_cipher
            encryptorName: aes_encryptor
            
props:
  sql-show: false